language: node_js
node_js:
  - "5"
  - "4"
addons:
  apt:
    packages:
      - wine
after_success:
  - |
    if test "$TRAVIS_TAG" ; then
      npm run build &&
      cd electron &&
      npm install &&
      npm run build &&
      npm run pkg &&
      cd pkg &&
      zip -q -r ../../glitch-linux.zip Glitch-linux-x64 &&
      zip -q -r ../../glitch-windows.zip Glitch-win32-ia32 &&
      zip -q -r ../../glitch-macosx.zip Glitch-darwin-x64 &&
      cd ../..
      ls -l
    fi
deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - glitch-linux.zip
    - glitch-windows.zip
    - glitch-macosx.zip
  skip_cleanup: true
  on:
    tags: true
